name: Upload coverage to Codecov
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            OS: ${{ env.RUNNER_OS }}
            PYTHON_VERSION: 3.8
        steps:
            - uses: actions/checkout@master
            - name: Setup Python
              uses: actions/setup-python@master
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pipenv myp
                  pipenv install
            - name: Generate coverage report
              run: |
                  myp run pytest-cov
            - name: Upload coverage to codecov.io
              run: pipenv run bash <(curl -s https://codecov.io/bash)
              if: always()
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
